# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cpg5japsA_zxjXId4mTYYvlvNN-bCZFC
"""

import nltk
print("Hi")
nltk.download('punkt')
from nltk.tokenize import word_tokenize
with open ('LDC2006T08.tml') as fin:
    tokens = word_tokenize(fin.read())
    print(tokens)
    print("---------AFTER tag-----------")
    print(tokens.count("AFTER"))
    print("---------BEFORE tag-----------")
    print(tokens.count("BEFORE"))